---
version: 2.1
orbs:
   railflow: railflow-1/railflow-1-orb@0.0.2

jobs:
  railflow_test:
    working_directory: ~/railflow-orb-test
    executor: railflow/default
    shell: /bin/bash --login -o pipefail
    environment:
      RAILFLOW_KEY: EEZWP-XFFIJ-BVMMJ-BTIXU
      RAILFLOW_URL:  http://railflow.com
      RAILFLOW_USERNAME: 03-veers.soups@icloud.com
      RAILFLOW_PASSWORD:
      RAILFLOW_PROJECT_NAME: tr_prj
      RAILFLOW_PROJECT_PATH:
      RAILFLOW_REPORT_FORMAT: testng
      RAILFLOW_REPORT_PATH:
      RAILFLOW_SEARCH_MODE: path
      RAILFLOW_TEST_PLAN: tr_testplan
      RAILFLOW_TEST_RUN: tr_testrun
      RAILFLOW_ASSIGN_FAILURE_TO: redcom@gmail.com
    steps:
      - railflow/test:
          RAILFLOW_KEY: $RAILFLOW_KEY
          RAILFLOW_URL: $RAILFLOW_URL
          RAILFLOW_USERNAME: $RAILFLOW_USERNAME
          RAILFLOW_PASSWORD: $RAILFLOW_PASSWORD
          RAILFLOW_PROJECT_NAME: $RAILFLOW_PROJECT_NAME
          RAILFLOW_PROJECT_PATH: $RAILFLOW_PROJECT_PATH
          RAILFLOW_REPORT_FORMAT: $RAILFLOW_REPORT_FORMAT
          RAILFLOW_REPORT_PATH: $RAILFLOW_REPORT_PATH
          RAILFLOW_SEARCH_MODE: $RAILFLOW_SEARCH_MODE
          RAILFLOW_TEST_PLAN: $RAILFLOW_TEST_PLAN
          RAILFLOW_TEST_RUN: $RAILFLOW_TEST_RUN
          RAILFLOW_ASSIGN_FAILURE_TO: $RAILFLOW_ASSIGN_FAILURE_TO

      - store_artifacts:
          path: $RAILFLOW_REPORT_PATH
          destination: railflow-artifacts

workflows:
  version: 2.1

  test:
    jobs:
      - railflow_test


